/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Victor Rivas
 */
public class Menu_ReservaGUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_ReservaGUI
     */
    public Menu_ReservaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Registrar_Profesor = new javax.swing.JButton();
        jBtn_Registra_reserva = new javax.swing.JButton();
        jBtn_Listar_Reserva = new javax.swing.JButton();
        jBtn_Registrar_Equipo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTf_Reserva = new javax.swing.JTextField();
        jTf_Profersor = new javax.swing.JTextField();
        jTf_Equipo = new javax.swing.JTextField();
        jBtn_buscar_reserva = new javax.swing.JButton();
        jBtn_buscar_profesor = new javax.swing.JButton();
        jBtn_buscar_Equipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtn_Registrar_Profesor.setText("Registrar Profesor");

        jBtn_Registra_reserva.setText("Registrar reserva");

        jBtn_Listar_Reserva.setText("Listar Reserva");
        jBtn_Listar_Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Listar_ReservaActionPerformed(evt);
            }
        });

        jBtn_Registrar_Equipo.setText("Registrar Equipo");
        jBtn_Registrar_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Registrar_EquipoActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu de reservas");

        jTf_Reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTf_ReservaActionPerformed(evt);
            }
        });

        jTf_Profersor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTf_ProfersorActionPerformed(evt);
            }
        });

        jTf_Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTf_EquipoActionPerformed(evt);
            }
        });

        jBtn_buscar_reserva.setText("Buscar Reserva: ");
        jBtn_buscar_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_buscar_reservaActionPerformed(evt);
            }
        });

        jBtn_buscar_profesor.setText("Buscar Profesor");

        jBtn_buscar_Equipo.setText("Buscar Equipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtn_buscar_reserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBtn_Registrar_Profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn_Registrar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn_buscar_Equipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_buscar_profesor, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTf_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_Registra_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTf_Profersor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTf_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_Listar_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTf_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_buscar_reserva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTf_Profersor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_buscar_profesor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTf_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_buscar_Equipo))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Registra_reserva)
                    .addComponent(jBtn_Registrar_Profesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Listar_Reserva)
                    .addComponent(jBtn_Registrar_Equipo))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_Registrar_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Registrar_EquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_Registrar_EquipoActionPerformed

    private void jBtn_Listar_ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Listar_ReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_Listar_ReservaActionPerformed

    private void jTf_ReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTf_ReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_ReservaActionPerformed

    private void jTf_ProfersorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTf_ProfersorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_ProfersorActionPerformed

    private void jTf_EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTf_EquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_EquipoActionPerformed

    private void jBtn_buscar_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_buscar_reservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_buscar_reservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_ReservaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_ReservaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_ReservaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_ReservaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_ReservaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtn_Listar_Reserva;
    public javax.swing.JButton jBtn_Registra_reserva;
    public javax.swing.JButton jBtn_Registrar_Equipo;
    public javax.swing.JButton jBtn_Registrar_Profesor;
    public javax.swing.JButton jBtn_buscar_Equipo;
    public javax.swing.JButton jBtn_buscar_profesor;
    public javax.swing.JButton jBtn_buscar_reserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jTf_Equipo;
    public javax.swing.JTextField jTf_Profersor;
    public javax.swing.JTextField jTf_Reserva;
    // End of variables declaration//GEN-END:variables
}
